"""create staging_rows

Revision ID: 0e243cbc913b
Revises: 5ab64e68194b
Create Date: 2026-07-24 20:52:49.689658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e243cbc913b'
down_revision: Union[str, None] = '5ab64e68194b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staging_rows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('sheet_name', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('row_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_staging_rows_client_sheet', 'staging_rows', ['client_id', 'sheet_name'], unique=False)
    op.create_index('idx_staging_rows_source_file', 'staging_rows', ['client_id', 'source_file'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_staging_rows_source_file', table_name='staging_rows')
    op.drop_index('idx_staging_rows_client_sheet', table_name='staging_rows')
    op.drop_table('staging_rows')
    # ### end Alembic commands ###
