"""add retrieval_top_k and rrf_k to client_config

Revision ID: 32f61443e199
Revises: 83b89604b9c4
Create Date: 2026-07-28 10:42:15.022488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f61443e199'
down_revision: Union[str, None] = '83b89604b9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_config', sa.Column('retrieval_top_k', sa.Integer(), server_default='5', nullable=False))
    op.add_column('client_config', sa.Column('rrf_k', sa.Integer(), server_default='60', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_config', 'rrf_k')
    op.drop_column('client_config', 'retrieval_top_k')
    # ### end Alembic commands ###
