"""create schema_registry

Revision ID: 48d3c854b890
Revises: 7ec06e4ca8ba
Create Date: 2026-07-23 00:34:49.315175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48d3c854b890'
down_revision: Union[str, None] = '7ec06e4ca8ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_registry',
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('sheet_name', sa.String(), nullable=False),
    sa.Column('columns', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('bucket', sa.String(), server_default='VECTOR_DB', nullable=False),
    sa.Column('mandatory_fields', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('client_id', 'sheet_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_registry')
    # ### end Alembic commands ###
