"""add admin_api_key to client_config

Revision ID: 5ab64e68194b
Revises: 5ef02a92a86f
Create Date: 2026-07-23 23:03:15.519366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab64e68194b'
down_revision: Union[str, None] = '5ef02a92a86f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_config', sa.Column('admin_api_key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'client_config', ['admin_api_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_config', type_='unique')
    op.drop_column('client_config', 'admin_api_key')
    # ### end Alembic commands ###
