"""create token_cache

Revision ID: 5ef02a92a86f
Revises: 48d3c854b890
Create Date: 2026-07-23 14:30:59.877042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef02a92a86f'
down_revision: Union[str, None] = '48d3c854b890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_cache',
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('encrypted_cache', sa.LargeBinary(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_cache')
    # ### end Alembic commands ###
