"""drop bucket from schema_registry and staging_rows

Revision ID: 758e60f1e41a
Revises: a81a690b9d24
Create Date: 2026-08-07 23:29:16.033432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758e60f1e41a'
down_revision: Union[str, None] = 'a81a690b9d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schema_registry', 'bucket')
    op.drop_column('staging_rows', 'bucket')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staging_rows', sa.Column('bucket', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('schema_registry', sa.Column('bucket', sa.VARCHAR(), server_default=sa.text("'VECTOR_DB'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
