"""create knowledge_chunks and client_config

Revision ID: 7ec06e4ca8ba
Revises: 
Create Date: 2026-07-22 23:04:17.658999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ec06e4ca8ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_config',
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('allowed_metadata_keys', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('boilerplate_threshold', sa.Float(), server_default='0.9', nullable=False),
    sa.Column('onedrive_item_id', sa.String(), nullable=True),
    sa.Column('embedding_backend_override', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('chunk_type', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chunks_client', 'knowledge_chunks', ['client_id'], unique=False)
    op.create_index('idx_chunks_embedding_hnsw', 'knowledge_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_chunks_metadata', 'knowledge_chunks', ['metadata'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunks_metadata', table_name='knowledge_chunks', postgresql_using='gin')
    op.drop_index('idx_chunks_embedding_hnsw', table_name='knowledge_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_chunks_client', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_table('client_config')
    # ### end Alembic commands ###
