"""add onedrive_drive_id to client_config

Revision ID: a0db1131db2f
Revises: 0e243cbc913b
Create Date: 2026-07-26 18:39:35.504537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0db1131db2f'
down_revision: Union[str, None] = '0e243cbc913b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_config', sa.Column('onedrive_drive_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_config', 'onedrive_drive_id')
    # ### end Alembic commands ###
