"""add full-text search GIN index to knowledge_chunks

Revision ID: a81a690b9d24
Revises: 32f61443e199
Create Date: 2026-07-28 20:40:04.704849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81a690b9d24'
down_revision: Union[str, None] = '32f61443e199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_chunks_content_fts', 'knowledge_chunks', [sa.text("to_tsvector('simple', content)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunks_content_fts', table_name='knowledge_chunks', postgresql_using='gin')
    # ### end Alembic commands ###
