"""create chat_history intent_log dialogue_state_template_map and add whatsapp retrieval top_k columns

Revision ID: deb4535fe6cf
Revises: 758e60f1e41a
Create Date: 2026-08-11 19:59:04.904791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb4535fe6cf'
down_revision: Union[str, None] = '758e60f1e41a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_history_client_session', 'chat_history', ['client_id', 'session_id', 'created_at'], unique=False)
    op.create_table('dialogue_state_template_map',
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('dialogue_state', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('client_id', 'dialogue_state')
    )
    op.create_table('intent_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('modality', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('routing_outcome', sa.String(), nullable=False),
    sa.Column('resolution_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intent_log_client_created', 'intent_log', ['client_id', 'created_at'], unique=False)
    op.create_index('idx_intent_log_client_intent', 'intent_log', ['client_id', 'intent'], unique=False)
    op.add_column('client_config', sa.Column('whatsapp_retrieval_top_k_narrow', sa.Integer(), server_default='1', nullable=False))
    op.add_column('client_config', sa.Column('whatsapp_retrieval_top_k_broad', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_config', 'whatsapp_retrieval_top_k_broad')
    op.drop_column('client_config', 'whatsapp_retrieval_top_k_narrow')
    op.drop_index('idx_intent_log_client_intent', table_name='intent_log')
    op.drop_index('idx_intent_log_client_created', table_name='intent_log')
    op.drop_table('intent_log')
    op.drop_table('dialogue_state_template_map')
    op.drop_index('idx_chat_history_client_session', table_name='chat_history')
    op.drop_table('chat_history')
    # ### end Alembic commands ###
