"""drop boilerplate_threshold from client_config

Revision ID: ff0b5276e5cb
Revises: a0db1131db2f
Create Date: 2026-07-27 14:08:25.026750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff0b5276e5cb'
down_revision: Union[str, None] = 'a0db1131db2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_config', 'boilerplate_threshold')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_config', sa.Column('boilerplate_threshold', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.9'::double precision"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
