import os
import re

from models.enums.BucketEnum import BucketEnum

_TEMPLATES_CLIENTS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "stores", "llm", "templates", "clients",
)

_FILENAME_BY_BUCKET = {
    BucketEnum.PROMPT_TEMPLATE: "prompt_templates.py",
    BucketEnum.SYSTEM_DIRECTIVE: "system_directives.py",
}


def _slugify(value) -> str:
    """Turns arbitrary cell/sheet text into a valid, readable Python
    identifier fragment. Non-ASCII letters (Arabic included) are kept
    as-is — Python 3 identifiers support Unicode letters natively
    (PEP 3131), and the whole point of claude.md §3.6 is that this text
    carries real semantic meaning worth preserving, not transliterating."""
    value = str(value).strip()
    value = re.sub(r"[^\w]+", "_", value, flags=re.UNICODE)
    value = value.strip("_")
    if not value:
        value = "field"
    if value[0].isdigit():
        value = f"_{value}"
    return value


def _render_row_content(row_data: dict) -> str:
    """Deterministic field concatenation — walks the row's columns in the
    order they were discovered, skips empty cells, joins as 'label: value'.
    Same mechanism for every sheet and every client; no boilerplate
    detection here (that's Step 6, and Bucket-A-only)."""
    parts = [
        f"{label}: {value}"
        for label, value in row_data.items()
        if label != "sheet_name" and value is not None and str(value).strip() != ""
    ]
    return ". ".join(parts)


def write_template_file(client_id: str, bucket: BucketEnum, rows: list[dict]) -> str:
    """The only code allowed to write stores/llm/templates/clients/<client_id>/*.py
    (claude.md §3.5). Fully overwrites the target module every call — the
    file-based equivalent of delete-and-reinsert. Never special-cases a
    sheet or a client: template_id is derived mechanically from sheet_name
    plus the row's own first populated field."""
    if bucket not in _FILENAME_BY_BUCKET:
        raise ValueError(f"write_template_file only handles Bucket B/C, got {bucket!r}")

    client_dir = os.path.join(_TEMPLATES_CLIENTS_DIR, client_id)
    os.makedirs(client_dir, exist_ok=True)

    init_path = os.path.join(client_dir, "__init__.py")
    if not os.path.exists(init_path):
        open(init_path, "w", encoding="utf-8").close()

    used_ids: dict[str, int] = {}
    lines = [
        "from string import Template",
        "",
        "# Auto-generated by utils/template_file_writer.py — DO NOT EDIT BY HAND.",
        f"# Fully regenerated on every sync for client_id={client_id!r}.",
        "",
    ]

    for row_data in rows:
        sheet_name = row_data.get("sheet_name", "")
        first_value = next(
            (
                value for key, value in row_data.items()
                if key != "sheet_name" and value is not None and str(value).strip() != ""
            ),
            "",
        )

        base_id = f"{_slugify(sheet_name)}__{_slugify(first_value)}"
        used_ids[base_id] = used_ids.get(base_id, 0) + 1
        template_id = base_id if used_ids[base_id] == 1 else f"{base_id}_{used_ids[base_id]}"

        content = _render_row_content(row_data)
        lines.append(f"{template_id} = Template({content!r})")

    file_path = os.path.join(client_dir, _FILENAME_BY_BUCKET[bucket])
    with open(file_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    return file_path
